### PR TITLE
Added the 'running' function to determine if the ZoneMinder server is running

### PR DESCRIPTION
**Pull request by joro75**
Added the the 'running' function to ZMApi, which can be used to determine if the ZoneMinder is running or not. 
Using the 'start' or 'stop' functions this 'running' state can then be changed.

### CODE REVIEW

**Comment by pliablepixels** [comment]
What on earth! I never received any notifications of any of these PRS! I'll look into them this weekend. Are the issues still valid?

**Comment by pliablepixels** [comment]
The intent of this api almost seems to be a True or False whereas we are returning the HTTP response of daemonCheck. How about we simplify the response, or modify the API intent?

**Comment by joro75** [comment]
I agree that the 'running' function indeed seems to indicate that a True or False value is being returned. This is however not the case as it is returning the JSON response of the query. 
It is indeed confusing. I initially chose to return the JSON response as this is also the behaviour of the 'start', 'stop', 'restart' and 'set_state' functions. I wanted to maintain a similar behaviour.

I do prefer to change the API of the 'running' function to just return a single boolean value. 
If you agree, I can adjust the 'running' function.

**Comment by pliablepixels** [comment]
How about we return a JSON object:
isRunning: true/false
responseText: whatever daemonCheck responds?

**Comment by joro75** [comment]
Also OK. I will modify the implementation to return a JSON object as you suggested. 
Will try to do it in within 2 weeks.

**Comment by joro75** [comment]
Sorry, made a mesh of the rebase and the previous commit. 
Let's close this Pull Request, and forget it's change.

**Pull request closed without merging**
