### PR TITLE
Fix bug where an event delete would raise a BAD_IMAGE error

### PR DESCRIPTION
**Pull request by LukeARohl**

### CODE REVIEW

**Comment by Ilia-SB** [comment]
I am also having this problem with deleting events:
```
Traceback (most recent call last):
  File "/var/lib/zmeventnotification/bin/autodelete.py", line 62, in <module>
    event.delete()
  File "/usr/local/lib/python3.8/dist-packages/pyzm/helpers/Event.py", line 103, in delete
    return self.api._make_request(url=url, type='delete')
  File "/usr/local/lib/python3.8/dist-packages/pyzm/api.py", line 332, in _make_request
    raise ValueError ("BAD_IMAGE")
ValueError: BAD_IMAGE
```
Any chance this PR gets merged?

**Comment by LukeARohl** [comment]
The last update was Nov of 2021, I'm not holding my breath.

**Comment by connortechnology** [comment]
Sorry to take so long, just getting into zmes dev myself.

**Comment by LukeARohl** [comment]
Thanks for the merge!

**Pull request merged**
